import React, { useEffect, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { createRoot } from 'react-dom/client'
import config from './config.json'
import './style.css'

const products=config.products.map(([id,name,category,price,oldPrice,description])=>({id,name,category,price,oldPrice,description}))
const money=n=>new Intl.NumberFormat('fr-FR',{style:'currency',currency:'USD'}).format(n)
const key=config.theme+'-cart'
function load(){try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value.filter(i=>i&&products.some(p=>p.id===i.id)&&Number.isInteger(i.qty)&&i.qty>0).map(i=>({...i,qty:Math.min(20,i.qty)})):[]}catch{return []}}
function Photo({id,...props}){return <img src={'/images/'+id+'.webp'} loading={id==='hero'?'eager':'lazy'} {...props}/>}
function App(){
 const [cart,setCart]=useState(load),[category,setCategory]=useState('Tout'),[notice,setNotice]=useState(''),[order,setOrder]=useState(null)
 const location=useLocation(),nav=useNavigate()
 useEffect(()=>{document.documentElement.dataset.theme=config.theme;document.title=config.brand+' | '+(config.theme==='christmas'?'Cadeaux de Noël':'Boutique du Nouvel An')},[])
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[location.pathname])
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(cart))}catch{}},[cart])
 const lines=cart.map(i=>({...products.find(p=>p.id===i.id),qty:i.qty})),count=lines.reduce((s,i)=>s+i.qty,0),subtotal=lines.reduce((s,i)=>s+i.qty*i.price,0),shipping=subtotal>=75||!subtotal?0:5
 const add=p=>{setCart(items=>{const found=items.find(i=>i.id===p.id);return found?items.map(i=>i.id===p.id?{...i,qty:Math.min(20,i.qty+1)}:i):[...items,{id:p.id,qty:1}]});setNotice(p.name+' : ajouté au panier')}
 const quantity=(id,qty)=>setCart(items=>qty<1?items.filter(i=>i.id!==id):items.map(i=>i.id===id?{...i,qty:Math.min(20,qty)}:i))
 const summary=<aside className="summary"><p className="eyebrow">Le récapitulatif</p><h2>Votre commande</h2><div><span>Sous-total</span><b>{money(subtotal)}</b></div><div><span>Livraison</span><b>{shipping?money(shipping):'Offerte'}</b></div><div className="total"><span>Total</span><b>{money(subtotal+shipping)}</b></div><p className="muted">{shipping?'Livraison offerte dès 75 $US.':'Votre livraison est offerte.'}</p></aside>
 const empty=<section className="empty"><span className="large-mark">{config.mark}</span><h1>Votre panier attend vos envies.</h1><p>Votre panier est vide. Découvrez nos coups de cœur.</p><Link className="button" to="/">Découvrir la collection ↗</Link></section>
 return <><div className="announcement">{config.announcement}<span>Livraison offerte dès 75 $US</span></div><header><Link to="/" className="brand">{config.mark} {config.brand}</Link><nav><Link to="/">Collection</Link><Link className="bag" to="/cart">Panier <b>{count}</b></Link></nav></header><main><Routes>
 <Route path="/" element={<><section className="hero"><Photo id="hero" alt={config.theme==='christmas'?'Cadeaux de Noël et bougies près d’un sapin décoré':'Soirée de réveillon avec coupes en cristal et décorations dorées'}/><div className="hero-content"><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}<br/><em>{config.accent}</em></h1><p>{config.description}</p><a className="button" href="#collection">{config.button} ↗</a><span className="hero-note">De petits détails. De beaux souvenirs.</span></div><span className="hero-label">{config.theme==='christmas'?'Un écrin de douceur':'Rendez-vous à minuit'}</span></section><div className="perks"><span>✧ Choisis avec soin, réalisés avec goût</span><span>✧ Livraison offerte dès 75 $US</span><span>✧ Un peu de joie dans chaque commande</span></div><section className="collection" id="collection"><div className="section-head"><div><p className="eyebrow">{config.theme==='christmas'?'Le plaisir de faire plaisir':'Que le compte à rebours commence'}</p><h2>{config.section}</h2><p className="muted">{config.sub}</p></div><span className="edition">LA SÉLECTION DE SAISON / 06</span></div><div className="filters" role="group" aria-label="Catégories de produits">{['Tout',...new Set(products.map(p=>p.category))].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid">{products.filter(p=>category==='Tout'||p.category===category).map(p=><article className="card" key={p.id}><Link className="product-image" to={'/product/'+p.id}><Photo id={p.id} alt={p.name}/><span className="tag">Coup de cœur</span></Link><div className="product-copy"><span className="category">{p.category}</span><h3><Link to={'/product/'+p.id}>{p.name}</Link></h3><div className="price-row"><span><strong>{money(p.price)}</strong> <s>{money(p.oldPrice)}</s></span><button onClick={()=>add(p)} aria-label={'Ajouter '+p.name+' au panier'}>Ajouter au panier +</button></div></div></article>)}</div></section><section className="feature"><Photo id={config.theme==='christmas'?1:5} alt={config.theme==='christmas'?'Coffret cadeau soigneusement composé':'Bougeoirs dorés'}/><div><p className="eyebrow">Bien plus qu’une fête</p><h2>{config.feature}</h2><p>{config.featureText}</p><a href="#collection" className="text-link">Découvrez vos favoris ↗</a></div></section>{count>0&&<div className="cart-toast"><span role="status">{notice||count+(count===1?' article dans votre panier':' articles dans votre panier')}</span><Link to="/cart">Voir le panier ({count}) →</Link></div>}</>}/>
 <Route path="/cart" element={lines.length?<section className="page"><p className="eyebrow">Vos envies réunies</p><h1>Votre panier</h1><div className="columns"><div>{lines.map(p=><article className="cart-line" key={p.id}><Photo id={p.id} alt={p.name}/><div><Link to={'/product/'+p.id}>{p.name}</Link><p className="muted">{money(p.price)} l’unité</p><div className="qty"><button onClick={()=>quantity(p.id,p.qty-1)} aria-label={'Diminuer la quantité : '+p.name}>−</button><span>{p.qty}</span><button onClick={()=>quantity(p.id,p.qty+1)} aria-label={'Augmenter la quantité : '+p.name}>+</button></div><button className="remove" onClick={()=>quantity(p.id,0)}>Retirer</button></div><b>{money(p.price*p.qty)}</b></article>)}<Link className="text-link" to="/">← Continuer mes achats</Link></div><div>{summary}<Link className="button full" to="/checkout">Passer commande →</Link></div></div></section>:empty}/>
 <Route path="/checkout" element={lines.length?<section className="page"><p className="eyebrow">Encore une petite étape</p><h1>Finalisez votre commande.</h1><div className="columns"><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setOrder({name:data.get('name'),total:subtotal+shipping});setCart([]);nav('/thank-you')}}><h2>Informations de livraison</h2><div className="fields">{[['name','Nom complet','text','name'],['email','Adresse e-mail','email','email'],['address','Adresse postale','text','street-address'],['city','Ville','text','address-level2'],['postal','Code postal','text','postal-code']].map(([name,label,type,auto])=><label key={name}>{label}<input name={name} type={type} autoComplete={auto} required minLength={name==='email'?undefined:2}/></label>)}</div><p className="muted demo">Commande de démonstration : aucun paiement ne sera prélevé et aucun colis ne sera expédié.</p><button className="button full">Confirmer la commande de démonstration · {money(subtotal+shipping)}</button><Link className="text-link" to="/cart">← Retour au panier</Link></form>{summary}</div></section>:empty}/>
 <Route path="/thank-you" element={<section className="empty"><span className="large-mark">{config.mark}</span><p className="eyebrow">{order?'Votre commande de démonstration est terminée':'Encore de belles découvertes'}</p><h1>{order?'Merci, '+order.name.split(' ')[0]+'.':'Votre prochain coup de cœur vous attend.'}</h1><p>{order?'Votre commande de démonstration de '+money(order.total)+' est confirmée. Aucun paiement n’a été prélevé.':'Découvrez notre collection de saison.'}</p><Link className="button" to="/">Retour à la collection ↗</Link></section>}/>
 <Route path="/product/:id" element={<Product products={products} add={add} notice={notice}/>}/>
 <Route path="*" element={<section className="empty"><h1>Cette page est introuvable.</h1><Link className="button" to="/">Retour à la collection</Link></section>}/>
 </Routes></main><footer><div><Link to="/" className="brand">{config.mark} {config.brand}</Link><p>{config.theme==='christmas'?'Un peu de magie, offert avec soin.':'Pour des soirées inoubliables.'}</p></div><div><Link to="/">La collection</Link><Link to="/cart">Votre panier</Link><span>Boutique de démonstration · Aucun paiement réel</span></div><small>© {new Date().getFullYear()} {config.brand}. Pour les moments qui comptent.</small></footer></>
}
function Product({products,add,notice}){const location=useLocation(),p=products.find(p=>String(p.id)===location.pathname.split('/').filter(Boolean).at(-1));if(!p)return <section className="empty"><h1>Produit introuvable</h1><Link to="/">Découvrir la collection</Link></section>;return <section className="page"><Link className="text-link" to="/">← La collection</Link><div className="product-detail"><Photo id={p.id} alt={p.name}/><div><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><p className="detail-price">{money(p.price)} <s>{money(p.oldPrice)}</s></p><p className="muted">{p.description}</p><button className="button" onClick={()=>add(p)}>Ajouter au panier +</button><p role="status">{notice}</p><Link className="text-link" to="/cart">Voir votre panier →</Link><div className="detail-note">Sélectionné avec soin pour la saison.<br/>Livraison offerte dès 75 $US.</div></div></div></section>}
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)

