import React, { useEffect, useState } from 'react'
import { BrowserRouter, Link, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { createRoot } from 'react-dom/client'
import config from './config.json'
import './style.css'

const products=config.products.map(([id,name,category,price,oldPrice,description])=>({id,name,category,price,oldPrice,description}))
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
const key=config.theme+'-cart'
function load(){try{const value=JSON.parse(localStorage.getItem(key));return Array.isArray(value)?value.filter(i=>i&&products.some(p=>p.id===i.id)&&Number.isInteger(i.qty)&&i.qty>0).map(i=>({...i,qty:Math.min(20,i.qty)})):[]}catch{return []}}
function Photo({id,...props}){return <img src={'/images/'+id+'.webp'} loading={id==='hero'?'eager':'lazy'} {...props}/>}
function App(){
 const [cart,setCart]=useState(load),[category,setCategory]=useState('All'),[notice,setNotice]=useState(''),[order,setOrder]=useState(null)
 const location=useLocation(),nav=useNavigate()
 useEffect(()=>{document.documentElement.dataset.theme=config.theme;document.title=config.brand+' | '+(config.theme==='christmas'?'Christmas gifts':'New Year party shop')},[])
 useEffect(()=>{window.scrollTo({top:0,behavior:'instant'})},[location.pathname])
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(cart))}catch{}},[cart])
 const lines=cart.map(i=>({...products.find(p=>p.id===i.id),qty:i.qty})),count=lines.reduce((s,i)=>s+i.qty,0),subtotal=lines.reduce((s,i)=>s+i.qty*i.price,0),shipping=subtotal>=75||!subtotal?0:5
 const add=p=>{setCart(items=>{const found=items.find(i=>i.id===p.id);return found?items.map(i=>i.id===p.id?{...i,qty:Math.min(20,i.qty+1)}:i):[...items,{id:p.id,qty:1}]});setNotice(p.name+' added to your bag')}
 const quantity=(id,qty)=>setCart(items=>qty<1?items.filter(i=>i.id!==id):items.map(i=>i.id===id?{...i,qty:Math.min(20,qty)}:i))
 const summary=<aside className="summary"><p className="eyebrow">The lovely details</p><h2>Your order</h2><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Shipping</span><b>{shipping?money(shipping):'On us'}</b></div><div className="total"><span>Total</span><b>{money(subtotal+shipping)}</b></div><p className="muted">{shipping?'Free shipping on orders $75+.':'You’ve unlocked free shipping.'}</p></aside>
 const empty=<section className="empty"><span className="large-mark">{config.mark}</span><h1>A little room for something lovely.</h1><p>Your bag is empty. Let’s find something you’ll love.</p><Link className="button" to="/">Explore the collection ↗</Link></section>
 return <><div className="announcement">{config.announcement}<span>Complimentary shipping over $75</span></div><header><Link to="/" className="brand">{config.mark} {config.brand}</Link><nav><Link to="/">Collection</Link><Link className="bag" to="/cart">Bag <b>{count}</b></Link></nav></header><main><Routes>
 <Route path="/" element={<><section className="hero"><Photo id="hero" alt={config.theme==='christmas'?'Warm Christmas gifts and candlelight beside a decorated tree':'A midnight celebration with crystal glasses and golden decorations'}/><div className="hero-content"><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}<br/><em>{config.accent}</em></h1><p>{config.description}</p><a className="button" href="#collection">{config.button} ↗</a><span className="hero-note">Small details. Beautiful memories.</span></div><span className="hero-label">{config.theme==='christmas'?'Wrapped in warmth':'Meet you at midnight'}</span></section><div className="perks"><span>✧ Carefully chosen, beautifully made</span><span>✧ Free shipping over $75</span><span>✧ A little joy in every order</span></div><section className="collection" id="collection"><div className="section-head"><div><p className="eyebrow">{config.theme==='christmas'?'The art of thoughtful gifting':'Let the countdown begin'}</p><h2>{config.section}</h2><p className="muted">{config.sub}</p></div><span className="edition">THE SEASONAL EDIT / 06</span></div><div className="filters" role="group" aria-label="Product categories">{['All',...new Set(products.map(p=>p.category))].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="grid">{products.filter(p=>category==='All'||p.category===category).map(p=><article className="card" key={p.id}><Link className="product-image" to={'/product/'+p.id}><Photo id={p.id} alt={p.name}/><span className="tag">Seasonal favorite</span></Link><div className="product-copy"><span className="category">{p.category}</span><h3><Link to={'/product/'+p.id}>{p.name}</Link></h3><div className="price-row"><span><strong>{money(p.price)}</strong> <s>{money(p.oldPrice)}</s></span><button onClick={()=>add(p)} aria-label={'Add '+p.name+' to bag'}>Add to bag +</button></div></div></article>)}</div></section><section className="feature"><Photo id={config.theme==='christmas'?1:5} alt={config.theme==='christmas'?'Thoughtfully arranged gift box':'Golden candle holders'}/><div><p className="eyebrow">More than a celebration</p><h2>{config.feature}</h2><p>{config.featureText}</p><a href="#collection" className="text-link">Discover your favorites ↗</a></div></section>{count>0&&<div className="cart-toast"><span role="status">{notice||count+' items in your bag'}</span><Link to="/cart">View bag ({count}) →</Link></div>}</>}/>
 <Route path="/cart" element={lines.length?<section className="page"><p className="eyebrow">Good things, all together</p><h1>Your bag</h1><div className="columns"><div>{lines.map(p=><article className="cart-line" key={p.id}><Photo id={p.id} alt={p.name}/><div><Link to={'/product/'+p.id}>{p.name}</Link><p className="muted">{money(p.price)} each</p><div className="qty"><button onClick={()=>quantity(p.id,p.qty-1)} aria-label={'Decrease '+p.name}>−</button><span>{p.qty}</span><button onClick={()=>quantity(p.id,p.qty+1)} aria-label={'Increase '+p.name}>+</button></div><button className="remove" onClick={()=>quantity(p.id,0)}>Remove</button></div><b>{money(p.price*p.qty)}</b></article>)}<Link className="text-link" to="/">← Keep exploring</Link></div><div>{summary}<Link className="button full" to="/checkout">Continue to checkout →</Link></div></div></section>:empty}/>
 <Route path="/checkout" element={lines.length?<section className="page"><p className="eyebrow">One last little step</p><h1>Make it yours.</h1><div className="columns"><form onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setOrder({name:data.get('name'),total:subtotal+shipping});setCart([]);nav('/thank-you')}}><h2>Delivery details</h2><div className="fields">{[['name','Full name','text','name'],['email','Email address','email','email'],['address','Street address','text','street-address'],['city','City','text','address-level2'],['postal','Postal code','text','postal-code']].map(([name,label,type,auto])=><label key={name}>{label}<input name={name} type={type} autoComplete={auto} required minLength={name==='email'?undefined:2}/></label>)}</div><p className="muted demo">This is a demo order. No payment is taken and nothing is shipped.</p><button className="button full">Place demo order · {money(subtotal+shipping)}</button><Link className="text-link" to="/cart">← Back to your bag</Link></form>{summary}</div></section>:empty}/>
 <Route path="/thank-you" element={<section className="empty"><span className="large-mark">{config.mark}</span><p className="eyebrow">{order?'Your demo order is complete':'A little more to discover'}</p><h1>{order?'Thank you, '+order.name.split(' ')[0]+'.':'Your next favorite is waiting.'}</h1><p>{order?'Your '+money(order.total)+' demo order is confirmed. No payment was taken.':'Explore our seasonal collection.'}</p><Link className="button" to="/">Back to the collection ↗</Link></section>}/>
 <Route path="/product/:id" element={<Product products={products} add={add} notice={notice}/>}/>
 <Route path="*" element={<section className="empty"><h1>This page has wandered off.</h1><Link className="button" to="/">Back to the collection</Link></section>}/>
 </Routes></main><footer><div><Link to="/" className="brand">{config.mark} {config.brand}</Link><p>{config.theme==='christmas'?'A little wonder, thoughtfully given.':'For nights that become stories.'}</p></div><div><Link to="/">The collection</Link><Link to="/cart">Your bag</Link><span>Demo store · No real payments</span></div><small>© {new Date().getFullYear()} {config.brand}. Made for the moments.</small></footer></>
}
function Product({products,add,notice}){const location=useLocation(),p=products.find(p=>String(p.id)===location.pathname.split('/').filter(Boolean).at(-1));if(!p)return <section className="empty"><h1>Product not found</h1><Link to="/">Explore the collection</Link></section>;return <section className="page"><Link className="text-link" to="/">← The collection</Link><div className="product-detail"><Photo id={p.id} alt={p.name}/><div><p className="eyebrow">{p.category}</p><h1>{p.name}</h1><p className="detail-price">{money(p.price)} <s>{money(p.oldPrice)}</s></p><p className="muted">{p.description}</p><button className="button" onClick={()=>add(p)}>Add to bag +</button><p role="status">{notice}</p><Link className="text-link" to="/cart">View your bag →</Link><div className="detail-note">Beautifully chosen for the season.<br/>Complimentary shipping on orders over $75.</div></div></div></section>}
createRoot(document.getElementById('root')).render(<React.StrictMode><BrowserRouter><App/></BrowserRouter></React.StrictMode>)

